### ISSUE TITLE
Write a tutorial for Bazel + Go

### ISSUE THREAD

**Issue by cgrindel** [bazel-contrib/Bazel-learning-paths#5]
Look like the C++ and Java tutorials.

Assigned: Chris Love

**Comment by chrislovecnm** [comment]
@chrislovecnm btw @cgrindel

**Comment by chrislovecnm** [comment]
@alexeagle was saying to place the tutorial under https://github.com/bazel-contrib/SIG-rules-authors/tree/gh-pages for the time being.  I can then work with Radhika and the bazel team to see if it makes sense to move it under the bazel website.  That or we need a link from the bazel website to the bazel contrib gh pages site.

**Comment by cgrindel** [comment]
OK. If it is going to live there, let's keep the original issue as it is already in that repo.

Follow along at https://github.com/bazel-contrib/SIG-rules-authors/issues/60.
